services:
  arma3:
    build: .
    image: arma3-server:latest
    container_name: arma3-server
    network_mode: "host"
    cap_add: 
      - NET_ADMIN
    ports:
      - "2302:2302"
      - "2303:2303"
      - "2304:2304"
      - "2305:2305"
      - "2306:2306"
    env_file:
      - .env
    volumes:
      - ./arma:/arma:Z
      - ./arma/logs:/logs:Z
      - server_files:/server
      - credential_cache:/root/.local/
volumes:
  credential_cache:
    external: true
  server_files:
    external: true
