services:
  arma3:
    build: .
    image: arma3-server:latest
    container_name: arma3-server
    ports:
      - "2302:2302/udp"
      - "2303:2303/udp"
      - "2304:2304/udp"
      - "2305:2305/udp"
    env_file:
      - .env
    volumes:
      - ./arma:/opt/arma